### ISSUE TITLE
Seems to be broken with latest sphinx 1.7.6

### ISSUE THREAD

**Issue by chaoflow** [myyasuda/sphinxbootstrap4theme#2]
Thank you for making this theme available!

With sphinx 1.7.6 at least bullet lists and therefore table of contents and navigation seem to be broken.

![2018-08-07-110701_1424x745_scrot](https://user-images.githubusercontent.com/89596/43766292-5fa48d4e-9a32-11e8-9c82-e4a570b822c6.png)

**Comment by myyasuda** [comment]
Thank you for your feedback.

I uploaded fixed version (0.5.1) to PyPI.
Sorry, please build your document again with new version.

**Comment by chaoflow** [comment]
@myyasuda Thank you very much for the quick fix! Now the navbar gets correctly initialised.
