### ISSUE TITLE
Navbar wobbles vertically when scrolling in Firefox 61

### ISSUE THREAD

**Issue by chaoflow** [myyasuda/sphinxbootstrap4theme#3]
When scrolling vertically in Firefox 61 the navbar wobbles vertically. This does not happen with Chromium 67 

1. Visit: http://myyasuda.github.io/sphinxbootstrap4theme/examples.html
2. Click "Set up" in the navbar
3. Scrol vertically

**Comment by myyasuda** [comment]
I released modified version (0.5.2) of this issue.

**Comment by chaoflow** [comment]
Thanks a lot for another very quick fix!
