### ISSUE TITLE
Bootstrap version

### ISSUE THREAD

**Issue by chaoflow** [myyasuda/sphinxbootstrap4theme#4]
Currently, there are two bootstrap version included:

- https://github.com/myyasuda/sphinxbootstrap4theme/tree/master/themes/sphinxbootstrap4theme/static/bootstrap-4.0.0-alpha.5
- https://github.com/myyasuda/sphinxbootstrap4theme/tree/master/themes/sphinxbootstrap4theme/static/bootstrap-4.0.0-alpha3

Are both needed? Would it make sense to upgrade to the latest stable?

**Comment by myyasuda** [comment]
Sorry. This theme does not support the latest version.

Also, only alpha5 is enough. 
In the next version, I will delete alpha3 from the repository.

Regards.

**Comment by chaoflow** [comment]
@myyasuda Thank you for the quick response! Do you know what would break with the latest version? I'd be happy to help.

**Comment by myyasuda** [comment]
No, I do not know.
Sorry.

**Comment by chaoflow** [comment]
@myyasuda Any chance to get #6 merged and released?

**Comment by chaoflow** [comment]
@myyasuda Thank you for merging! A release to pypi would be superb.

**Comment by myyasuda** [comment]
Sorry for the late merge...
 Released merge version (v0.6.0).

**Comment by chaoflow** [comment]
@myyasuda thank you very much for the release!
